FROM riccardoblb/base:amd64

#Based on https://raw.githubusercontent.com/anapsix/docker-alpine-java/master/8/131b11/jdk/standard/Dockerfile

MAINTAINER Riccardo Balbo <riccardo0blb@gmail.com> 

ENV  JAVA_JCE=unlimited \
    JAVA_HOME=/opt/jdk \
    PATH=${PATH}:/opt/jdk/bin \
    GLIBC_VERSION=2.23-r3 \
    LANG=C.UTF-8

#COPY jdk.tar.gz /tmp/jdk.tar.gz
COPY jce_policy-8.zip /tmp/jce.zip

RUN set -ex && \
    apk upgrade --update && \
    apk add --update libstdc++ curl ca-certificates bash   &&\
    jdk_version="`curl -s https://ci_public_deploy.frk.wf/jdk8_latest.txt`" && \
    echo "Download java version $jdk_version" && \
    curl "https://ci_public_deploy.frk.wf/jdk8_lin64-$jdk_version.tar.gz" -o /tmp/jdk.tar.gz &&\
   for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION} glibc-i18n-${GLIBC_VERSION}; do curl -sSL https://github.com/andyshinn/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done && \
    apk add --allow-untrusted /tmp/*.apk && \
     rm -v /tmp/*.apk && \
    ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true ) && \
    echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh && \    
    /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib  &&\
   addgroup -g 1000 -S java  &&\
    adduser -u 1000 -S -D -G java java && \
    cd tmp &&\
    mkdir -p /opt/jdk &&\
    tar -xzf jdk.tar.gz -C /opt/jdk/ &&\
    rm -Rf jdk* &&\
    if [ "${JAVA_JCE}" == "unlimited" ]; then echo "Installing Unlimited JCE policy" >&2 && \
        cd /tmp &&\
        mkdir  jce_ex &&\
        unzip jce.zip -d jce_ex &&\
        mv jce_ex/*/*.jar /opt/jdk/jre/lib/security &&\
        rm -Rf jce*; \
    fi &&\
    chown -R java:java /opt/jdk &&\
    sed -i s/#networkaddress.cache.ttl=-1/networkaddress.cache.ttl=10/ $JAVA_HOME/jre/lib/security/java.security && \
    apk del curl glibc-i18n 
    
USER java